permissions:
  contents: write  # erlaubt commit & push über GITHUB_TOKEN

name: Python-Skript automatisch ausführen

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: {}

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install firefox

      - name: Run Python script
        id: run_script
        shell: bash
        env:
          FIBER_STATUS_URL: ${{ secrets.FIBER_STATUS_URL }}
          SMTP_HOST:        ${{ secrets.SMTP_HOST }}
          SMTP_PORT:        ${{ secrets.SMTP_PORT }}
          SMTP_USER:        ${{ secrets.SMTP_USER }}
          SMTP_PASS:        ${{ secrets.SMTP_PASS }}
          SMTP_TO:          ${{ secrets.SMTP_TO }}
        run: |
          set +e
          python glasfaserportal_notification.py
          code=$?
          echo "changed=$code" >> $GITHUB_OUTPUT
          # optional: echo "Exit-Code war $code"
          # und wir lassen die Shell jetzt mit 0 enden, damit der Job weiterläuft

      - name: Commit updated status
        if: steps.run_script.outputs.changed == '1'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add last_status.json
          git commit -m "chore: update last_status.json [skip ci]" || echo "Nothing to commit"
          git push
